import random
import click
import anyio
import mcp.types as types
from typing import Any
from pydantic import AnyUrl
from mcp.server.lowlevel import Server
from mcp.server.lowlevel.helper_types import ReadResourceContents

# --- Data ---

lies = [
    "The moon is made of recycled JavaScript.",
    "Drinking coffee makes you 40% better at algorithms.",
    "Git was invented specifically to make developers cry.",
    "The cloud is just someone else's very humid basement.",
    "AI stands for 'Awkward Intelligence'.",
    "Python is slow because it's sad.",
    "Every `null` pointer is a cry for help from the compiler.",
    "The first computer bug was actually a feature request.",
]

excuses = [
    "It works on my machine.",
    "The intern must have touched it.",
    "Mercury is in retrograde.",
    "I was going to fix that next sprint.",
    "That's not a bug, it's undocumented behavior.",
    "The tests were passing yesterday.",
    "Have you tried turning it off and on again?",
    "That's a known issue, it's in the backlog.",
    "It only happens in production.",
    "I didn't write that part.",
]

motivations = [
    "Let's circle back and leverage our synergies!",
    "Failure is just success that hasn't pivoted yet.",
    "Think outside the box, then disrupt the box.",
    "You're not behind, you're just early to being late.",
    "Every bug is an opportunity to grow as a person.",
    "Move fast and blame things.",
    "Your imposter syndrome is someone else's job security.",
    "Pain is just Agile without a retrospective.",
    "You miss 100% of the PRs you don't open.",
]

vibes = [
    "immaculate",
    "questionable",
    "chaotic but make it fashion",
    "suspiciously good",
    "mid at best",
    "certified unhinged",
    "off the charts",
    "technically present",
    "dangerously good",
    "needs calibration",
]

lorem_options = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Except none of this means anything.",
    "Pixel bacon ipsum dolor amet chuck short loin hamburger fatback drumstick — a sentence generated by a server with no ambitions.",
    "Hipster ipsum: pour-over artisan whatever, locavore chambray distillery trust fund 90's kogi.",
    "Corporate ipsum: leverage agile frameworks to provide a robust synopsis for high level overviews of iterative approaches.",
    "Zombie ipsum: Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro.",
]

advice_list = [
    "Have you tried sleeping on it?",
    "The answer is probably on Stack Overflow, page 2.",
    "Rewrite it in Rust.",
    "Add more semicolons.",
    "Just ship it, nobody reads the logs anyway.",
    "The real friends were the bugs we fixed along the way.",
    "When in doubt, console.log everything.",
    "Your future self will understand the code. Probably.",
    "Drink water. Touch grass. Then come back and refactor.",
]


# --- Tools ---

def ping(message: str | None = None) -> str:
    if message:
        return f"pong: {message}"
    return "pong"


def echo(text: str) -> str:
    return text


def tell_lie() -> str:
    return random.choice(lies)


def make_excuse() -> str:
    return random.choice(excuses)


def vibe_check(name: str) -> str:
    score = random.randint(1, 100)
    label = random.choice(vibes)
    return f"{name}'s vibe score: {score}/100 — {label}."


def motivate(name: str) -> str:
    return f"{name}, {random.choice(motivations)}"


# --- Prompts ---

def create_nonsense_messages(topic: str | None = None) -> list[types.PromptMessage]:
    topic_part = f" about {topic}" if topic else " about anything"
    prompt = (
        f"Write three paragraphs of highly professional, confident, corporate-sounding nonsense{topic_part}. "
        "Use buzzwords, fake statistics, and vague strategic language. "
        "It should sound authoritative but mean absolutely nothing."
    )
    return [
        types.PromptMessage(role="user", content=types.TextContent(type="text", text=prompt))
    ]


def create_overengineer_messages(thing: str | None = None) -> list[types.PromptMessage]:
    thing_part = thing if thing else "making a cup of tea"
    prompt = (
        f"Explain how to do '{thing_part}' as if it were a highly complex distributed systems problem. "
        "Include microservices, Kubernetes, event sourcing, a CAP theorem trade-off analysis, "
        "and at least one unnecessary acronym you invented yourself."
    )
    return [
        types.PromptMessage(role="user", content=types.TextContent(type="text", text=prompt))
    ]


# --- CLI ---

@click.command()
@click.option("--port", default=8000, help="Port to listen on for SSE")
@click.option(
    "--transport",
    type=click.Choice(["stdio", "sse", "streamable-http"]),
    default="stdio",
    help="Transport type",
)
def main(port: int, transport: str) -> int:

    app = Server("mcp-server-dummy")

    # Tools
    @app.list_tools()
    async def list_tools() -> list[types.Tool]:
        return [
            types.Tool(
                name="ping",
                title="Ping",
                description="Responds with pong. Optionally echoes a message.",
                inputSchema={
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string",
                            "description": "Optional message to echo back",
                        }
                    },
                },
            ),
            types.Tool(
                name="echo",
                title="Echo",
                description="Repeats back exactly what you send. Profound.",
                inputSchema={
                    "type": "object",
                    "required": ["text"],
                    "properties": {
                        "text": {
                            "type": "string",
                            "description": "Text to echo",
                        }
                    },
                },
            ),
            types.Tool(
                name="lie",
                title="Lie",
                description="Returns a confident, completely made-up fact.",
                inputSchema={
                    "type": "object",
                    "properties": {},
                },
            ),
            types.Tool(
                name="excuse",
                title="Excuse",
                description="Generates a professional excuse for any situation.",
                inputSchema={
                    "type": "object",
                    "properties": {},
                },
            ),
            types.Tool(
                name="vibe_check",
                title="Vibe Check",
                description="Scientifically measures a person's vibe score out of 100.",
                inputSchema={
                    "type": "object",
                    "required": ["name"],
                    "properties": {
                        "name": {
                            "type": "string",
                            "description": "Name of the person to vibe check",
                        }
                    },
                },
            ),
            types.Tool(
                name="motivate",
                title="Motivate",
                description="Delivers a hollow but enthusiastic motivational message.",
                inputSchema={
                    "type": "object",
                    "required": ["name"],
                    "properties": {
                        "name": {
                            "type": "string",
                            "description": "Name of the person to motivate",
                        }
                    },
                },
            ),
        ]

    @app.call_tool()
    async def call_tool(name: str, arguments: dict[str, Any]) -> list[types.ContentBlock]:
        if name == "ping":
            message = ping(arguments.get("message"))
        elif name == "echo":
            if "text" not in arguments:
                raise ValueError("Missing text")
            message = echo(arguments["text"])
        elif name == "lie":
            message = tell_lie()
        elif name == "excuse":
            message = make_excuse()
        elif name == "vibe_check":
            if "name" not in arguments:
                raise ValueError("Missing name")
            message = vibe_check(arguments["name"])
        elif name == "motivate":
            if "name" not in arguments:
                raise ValueError("Missing name")
            message = motivate(arguments["name"])
        else:
            raise ValueError(f"Unknown tool: {name}")

        return [{"type": "text", "text": message}]

    # Resources
    @app.list_resources()
    async def list_resources() -> list[types.Resource]:
        return [
            types.Resource(
                uri="dummy://status",
                name="System Status",
                description="Current system status. Always reassuring.",
                mimeType="text/plain",
            ),
            types.Resource(
                uri="dummy://lorem",
                name="Lorem Ipsum (Weird Edition)",
                description="Placeholder text, but make it interesting.",
                mimeType="text/plain",
            ),
            types.Resource(
                uri="dummy://advice",
                name="Random Advice",
                description="Unsolicited life advice of dubious quality.",
                mimeType="text/plain",
            ),
        ]

    @app.read_resource()
    async def read_resource(uri: AnyUrl):
        uri_str = str(uri)
        if uri_str == "dummy://status":
            return [
                ReadResourceContents(
                    content=f"Status: {random.choice(status_messages)}",
                    mime_type="text/plain",
                )
            ]
        elif uri_str == "dummy://lorem":
            return [
                ReadResourceContents(
                    content=random.choice(lorem_options),
                    mime_type="text/plain",
                )
            ]
        elif uri_str == "dummy://advice":
            return [
                ReadResourceContents(
                    content=random.choice(advice_list),
                    mime_type="text/plain",
                )
            ]
        else:
            raise ValueError(f"Unknown resource: {uri_str}")

    # Prompts
    @app.list_prompts()
    async def list_prompts() -> list[types.Prompt]:
        return [
            types.Prompt(
                name="nonsense",
                title="Professional Nonsense Generator",
                description="Generate corporate-sounding gibberish about any topic",
                arguments=[
                    types.PromptArgument(
                        name="topic",
                        description="Topic to generate nonsense about (optional)",
                        required=False,
                    ),
                ],
            ),
            types.Prompt(
                name="overengineer",
                title="Overengineering Explainer",
                description="Explain something simple as a distributed systems nightmare",
                arguments=[
                    types.PromptArgument(
                        name="thing",
                        description="The simple thing to overengineer (e.g. 'boiling an egg')",
                        required=False,
                    ),
                ],
            ),
        ]

    @app.get_prompt()
    async def get_prompt(
        name: str, arguments: dict[str, str] | None = None
    ) -> types.GetPromptResult:
        arguments = arguments or {}

        if name == "nonsense":
            return types.GetPromptResult(
                messages=create_nonsense_messages(topic=arguments.get("topic"))
            )
        elif name == "overengineer":
            return types.GetPromptResult(
                messages=create_overengineer_messages(thing=arguments.get("thing"))
            )
        else:
            raise ValueError(f"Unknown prompt: {name}")

    # Transport
    if transport == "sse":
        from mcp.server.sse import SseServerTransport
        from starlette.applications import Starlette
        from starlette.requests import Request
        from starlette.responses import Response
        from starlette.routing import Mount, Route

        sse = SseServerTransport("/messages/")

        async def handle_sse(request: Request):
            async with sse.connect_sse(request.scope, request.receive, request._send) as streams:  # type: ignore[reportPrivateUsage]
                await app.run(streams[0], streams[1], app.create_initialization_options())
            return Response()

        starlette_app = Starlette(
            debug=True,
            routes=[
                Route("/sse", endpoint=handle_sse, methods=["GET"]),
                Mount("/messages/", app=sse.handle_post_message),
            ],
        )

        import uvicorn
        uvicorn.run(starlette_app, host="127.0.0.1", port=port)

    elif transport == "streamable-http":
        from mcp.server.streamable_http_manager import StreamableHTTPSessionManager
        from starlette.applications import Starlette
        from starlette.middleware.cors import CORSMiddleware
        import contextlib

        session_manager = StreamableHTTPSessionManager(app=app)

        @contextlib.asynccontextmanager
        async def lifespan(starlette_app: Starlette):
            async with session_manager.run():
                yield

        starlette_app = Starlette(debug=True, lifespan=lifespan)
        starlette_app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )

        class MCPASGIApp:
            def __init__(self, session_manager):
                self.session_manager = session_manager

            async def __call__(self, scope, receive, send):
                await self.session_manager.handle_request(scope, receive, send)

        starlette_app.mount("/mcp", MCPASGIApp(session_manager))

        import uvicorn
        uvicorn.run(starlette_app, host="127.0.0.1", port=port)

    else:
        from mcp.server.stdio import stdio_server

        async def arun():
            async with stdio_server() as streams:
                await app.run(streams[0], streams[1], app.create_initialization_options())

        anyio.run(arun)

    return 0
