[project]
name = "mcp-server-dummy"
version = "0.1.0"
description = "A dummy MCP server with useless but fancy tools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.9.0",
    "click>=8.3.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.17.0",
]

[project.scripts]
mcp-server-dummy = "mcp_server_dummy.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
